# -*- coding: utf-8 -*-
"""startup_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITlJrgm80c_8RNMuwjWzCWB8-wSRd6Im
"""

import numpy as np
import pandas as pd
from numpy import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt

# Importing the dataset
dataset = pd.read_csv('50_Startups.csv')

len(dataset)

dataset.head()

dataset.shape

plt.scatter(dataset['Marketing Spend'], dataset['Profit'], alpha = 0.5)
plt.title('Scateer plot of Profit with Marketing Spend')
plt.xlabel('Marketing Spend')
plt.ylabel('Profit')
plt.show()

plt.scatter(dataset['R&D Spend'], dataset['Profit'], alpha = 0.5)
plt.title('Scateer plot of Profit with Marketing Spend')
plt.xlabel('R&D Spend')
plt.ylabel('Profit')
plt.show()

plt.scatter(dataset['Administration'], dataset['Profit'], alpha = 0.5)
plt.title('Scateer plot of Profit with Marketing Spend')
plt.xlabel('Administration')
plt.ylabel('Profit')
plt.show()

#create  the figure object
ax = dataset.groupby(['State'])['Profit'].mean().plot.bar(
    figsize = (10,5),
    fontsize = 14
)
#set the title
ax.set_title("Average profit for different states where the startups operate", fontsize = 20)

#Set x and y-labels
ax.set_xlabel("State", fontsize = 15)
ax.set_ylabel("Profit", fontsize = 15)

dataset.State.value_counts()

#Create dummy variables for the catgeorical variable state
dataset['NewYork_State'] = np.where(dataset['State']=='New York', 1, 0)
dataset['California_State'] = np.where(dataset['State']=='California', 1, 0)
dataset['Florida_State'] = np.where(dataset['State']=='Florida', 1, 0)
# Drop the original column State from the dataframe
dataset.drop(columns=['State'],axis=1,inplace=True)
dataset.head()

dependent_variable = 'Profit'
# Create a list of independent variables
independent_variables = list(set(dataset.columns.tolist()) - {dependent_variable})
independent_variables

# Create the data of independent variables
X = dataset[independent_variables].values
# Create the dependent variable data
y = dataset[dependent_variable].values
dataset[independent_variables]

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train[0:10]

# Transforming data
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train[0:10]

# Fitting Multiple Linear Regression to the Training set
regressor = LinearRegression()
regressor.fit(X_train, y_train)

regressor.intercept_

regressor.coef_

y_pred_train = regressor.predict(X_train)

y_train

# Predicting the Test set results
y_pred = regressor.predict(X_test)
#Predicted profit on the test data
y_pred

# Actual profits on test data
y_test

mean_squared_error(y_test, y_pred)

# Train performance
math.sqrt(mean_squared_error(y_train, y_pred_train))

# Test performance
math.sqrt(mean_squared_error(y_test, y_pred))

r2_score(y_train, y_pred_train)

